- name: 패키지 매니저가 설치한 Containerd 제거
  package:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
      - containerd
      - containerd.io

- name: Containerd 파일 다운로드
  get_url:
    url: "https://github.com/containerd/containerd/releases/download/v{{ containerd_version }}/containerd-{{ containerd_version }}-linux-{{ host_architecture }}.tar.gz"
    dest: "/tmp/containerd-{{ containerd_version }}-linux-{{ host_architecture }}.tar.gz"
    mode: 0644

- name: Containerd 압축 해제 및 /usr/local/bin 이동
  unarchive:
    src: "/tmp/containerd-{{ containerd_version }}-linux-{{ host_architecture }}.tar.gz"
    dest: /usr/local/bin
    remote_src: yes
    extra_opts: [--strip-component=1]

- name: Containerd 서비스 파일 복사 위치 생성
  file:
    path: "/usr/local/lib/systemd/system"
    state: directory
    mode: 0755
    owner: root
    group: root
    recurse: yes

- name: Containerd 서비스 파일 복사
  copy:
    src: "files/containerd.service"
    dest: "/usr/local/lib/systemd/system/containerd.service"
    mode: 0644

  
- name: Containerd config 파일 복사 위치 생성
  file:
    path: "/etc/containerd"
    state: directory
    mode: 0755
    owner: root
    group: root
    recurse: yes

- name: Containerd config 파일 복사
  copy:
    src: "files/config.toml"
    dest: "/etc/containerd/config.toml"
    mode: 0644

- name: 시스템 데몬 reload
  systemd:
    daemon_reload: yes

- name: Containerd 서비스 시작
  service:
    name: containerd
    state: started
    enabled: yes


- name: runc 파일 다운로드
  get_url:
    url: "https://github.com/opencontainers/runc/releases/download/v{{ runc_version }}/runc.{{ host_architecture }}"
    dest: "/tmp/runc.{{ host_architecture }}"
    mode: 0755

- name: runc 설치
  command: install -m 0755 -o root -g root /tmp/runc.{{ host_architecture }} /usr/local/sbin/runc
  become: true


- name: cni 플러그인 파일 다운로드
  get_url:
    url: "https://github.com/containernetworking/plugins/releases/download/v{{ cni_plugins_version }}/cni-plugins-linux-{{ host_architecture }}-v{{ cni_plugins_version }}.tgz"
    dest: "/tmp/cni-plugins-linux-{{ host_architecture }}-v{{ cni_plugins_version }}.tgz"
    mode: 0644

- name: cni 플러그인 디렉터리 생성
  file:
    path: /opt/cni/bin
    state: directory
    mode: 0755
    owner: root
    group: root
    recurse: yes

- name: cni 플러그인 압축 해제 및 /opt/cni/bin 이동
  unarchive:
    src: "/tmp/cni-plugins-linux-{{ host_architecture }}-v{{ cni_plugins_version }}.tgz"
    dest: /opt/cni/bin
    remote_src: yes
    extra_opts: [--strip-component=1]
