_host_architecture_groups:
  x86_64: amd64
  aarch64: arm64
  armv7l: arm
host_architecture: >-
  {%- if ansible_architecture in _host_architecture_groups -%}
  {{ _host_architecture_groups[ansible_architecture] }}
  {%- else -%}
  {{ ansible_architecture }}
  {%- endif -%}

first_kube_control_plane_address: "{{ hostvars[groups['master'][0]]['ansible_host'] }}"
kube_apiserver_count: "{{ groups['master'] | length }}"
