# Recreate from : https://github.com/kubernetes-sigs/kubespray/blob/master/extra_playbooks/roles/kubernetes/control-plane/tasks/define-first-kube-control.yml#L20

- name: 컨트롤 플레인 노드 확인
  command: "{{ bin_dir }}/kubectl get nodes --selector=node-role.kubernetes.io/control-plane -o json"
  register: kube_control_planes_raw
  ignore_errors: yes
  changed_when: false

- debug: msg="kube_control_planes_raw :{{ kube_control_planes_raw }}"

- name: joined_control_planes 변수 설정
  set_fact:
    joined_control_planes: "{{ ((kube_control_planes_raw.stdout | from_json)['items']) | default([]) | map(attribute='metadata') | map(attribute='name') | list }}"
  delegate_to: item
  loop: "{{ groups['master'] }}" # 인벤토리에서 컨트롤 플레인 그룹 명 주의. 현재는 master로 되어있고 나중에 변경 할 수도 있음.
  when: kube_control_planes_raw is succeeded
  run_once: yes

- name: first_kube_control_plane 변수 설정
  set_fact:
    first_kube_control_plane: "{{ joined_control_planes | default([]) | first | default(groups['master'] | first) }}"

# 이 작업이 필요한 이유는, 부트스트래핑 토큰이 만료 된 이후에 새로운 컨트롤 플레인 노드 / 워커 노드를 추가하기 위해 
# 만료된 부트스트랩 토큰을 제거하고 재발급하고, 그 토큰을 사용하는 과정이 필요한데, 모든 컨트롤 플레인 노드에서 수행 될 필요 없이
# 하나의 컨트롤 플레인에서만 수행되면 되기때문입니다.

# - debug: msg="joined_control_planes :{{ joined_control_planes }}"

- debug: msg="first_kube_control_plane :{{ first_kube_control_plane }}"
