apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
bootstrapTokens:
  - groups:
      - system:bootstrappers:kubeadm:default-node-token
    token: abcdef.0123456789abcdef # Move to template variable
    ttl: 0h30m0s
    usages:
      - signing
      - authentication
localAPIEndpoint:
  advertiseAddress: 192.168.201.12
  bindPort: 6443
nodeRegistration:
  criSocket: unix:///var/run/containerd/containerd.sock
  imagePullPolicy: IfNotPresent
  taints: []
certificateKey: "acca4374af5ed236a2130987a1ddff1aac1441146b5b51dc8b613af1dc4938d4"
# skipPhases:
#   - addon/kube-proxy
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
apiServer:
  extraArgs:
    apiserver-count: "3"
certificatesDir: /etc/kubernetes/pki
clusterName: utm-test
controllerManager: {}
dns: {}
etcd:
  local:
    dataDir: /var/lib/etcd
imageRepository: registry.k8s.io
kubernetesVersion: 1.29.1
networking:
  dnsDomain: cluster.local
  serviceSubnet: 172.16.0.0/16
  podSubnet: 10.101.0.0/16
scheduler: {}

#TEST
controlPlaneEndpoint: 192.168.201.12:6443
# cerficatesDir: /etc/kubernetes/pki
# cerfiticatesDir: <- 이거 아마 해당 경로에 인증서 만들라는 옵션 같은데. 검색해봐야 함

---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
cgroupDriver: systemd

